<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DtReader.Core\DtReader.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Sql\**\*.sql" />
    </ItemGroup>

</Project>
