<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="dbup" Version="5.0.41" />
        <PackageReference Include="dbup-sqlite" Version="6.0.1" />
        <EmbeddedResource Include="Sql\**\*.sql" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\DtReader.Core\DtReader.Core.csproj" />
    </ItemGroup>

</Project>
